#!/bin/bash

SELECTION=$(echo -e "Whole Screen\nRectangle" | dmenu)
if [ "$SELECTION" = "" ]; then
    # $var is empty
    exit
fi

case $SELECTION in
    "Whole Screen")
        MONP=$(~/scripts/select_monitor.sh)
        ;;
    "Rectangle")
        MONP=$(slop -f "%wx%h +%x,%y")
        ;;
esac

if [ "$MONP" = "" ]; then
    exit
fi

DIM=$(echo $MONP | awk '{print $1}')
OFF=$(echo $MONP | awk '{print $2}')

sleep 0.1 # wait for dmenu to close
ffmpeg -f x11grab -video_size $DIM -i $DISPLAY$OFF -vframes 1 "$HOME/Pictures/$(date +%d-%b-%g-%H:%m:%S).png"
