#!/bin/bash

# pamixer to get: muted (display different speaker emoji),
# and current sound volume
function sound_status {
    VOL=$(pamixer --get-volume)
    MUTED=$(pamixer --get-mute)
    case $MUTED in
        "true" )  echo -n 🔇;;
        "false")  echo -n 🔊;;
    esac

    echo -n " $VOL%"
}

# get current assigned ip address in LAN network
function getip {
    echo "$(ip addr show dev $(ip r | grep -oP 'default.*dev \K\S*') | grep -oP '(?<=inet )[^/]*(?=/)')"
}

# get current layout (hardcoded)
function getlayout {
    echo -n $(xkblayout)
}

# /proc/status narrowed down to cpu usage
function cpuavg {
    printf "%.2f\n" $(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')
}

function minikubestat {
    if [[ ! -z "$(command -v minikube)" ]]; then
        mstatus=$(minikube status | grep host)
        if [[ $mstatus == *"Running"* ]]; then
            echo kube
        fi
    fi
}

function bright {
    BRIGHT=$(xbacklight -get | xargs printf "%.0f")
    if [[ ! -z "$BRIGHT" ]]; then
        echo -n "$BRIGHT"
    fi
}

function bat {
    if [[ ! -z "$(command -v acpi)" ]]; then
        echo -n ⚡ $(acpi -b | awk '{print $4}' | tr -d ",")
    fi
}
while true; do
    xsetroot -name "CPU: $(cpuavg)%  🌐 $(getip) 🖮 $(getlayout) $(sound_status) | $(bat) | 📆 $(date "+%d/%m/%y 🕒 %H:%M") 💻 $(bright)"
    sleep 1s
done
