#!/bin/bash

# pamixer to get: muted (display different speaker emoji),
# and current sound volume
function sound_status {
    VOL=$(pamixer --get-volume)
    MUTED=$(pamixer --get-mute)
    echo -ne "\x05 "
    case $MUTED in
        "true" )  echo -ne 🔇;;
        "false")  echo -ne 🔊;;
    esac

    echo -ne " $VOL% "
    echo -ne "\x01"
}

# get current assigned ip address in LAN network
function getip {
    echo -ne "\x08$(ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')\x01"
}

# get current layout (hardcoded)
function getlayout {
    echo -ne "\x09 $(xkblayout) \x01"
}

# /proc/status narrowed down to cpu usage
function cpuavg {
    echo -ne "%.2f\n" $(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')
}

function bright {
    BRIGHT=$(xbacklight -get | xargs printf "%.0f")
    if [[ ! -z "$BRIGHT" ]]; then
        echo -ne "\x07 💻$BRIGHT \x01"
    fi
}

function bat {
    if [[ ! -z "$(command -v acpi)" ]]; then
        if [[ ! -z "$(acpi -b | grep Charging)" ]]; then
            STAT="\x0A 🔌"
        else
            # \x06
            STAT="\x06 ⚡"
        fi
        echo -ne "$STAT "$(acpi -b | awk '{print $4}' | tr -d ",")" \x01"
    fi
}

function datetime {
    DAT=$(date "+%d/%m/%y 🕒 %H:%M")

    echo -ne "\x0B 📆 $DAT \x01"
}

while true; do
    xsetroot -name "$(getip)$(getlayout)$(sound_status)$(bat)$(datetime)$(bright)"
    sleep 1s
done
